### ISSUE TITLE
mp4 file in skipsilence 2 no audio detected

### ISSUE THREAD

**Issue by tillhanke** [vantezzen/skip-silence#14]
Love this extension and used it a lot the last weeks. But suddenly after the update it doesnt detect the audio anymore. I activated file-url access but this does not solve the problem.
On Youtube it still works fine though. Only file Urls wont work.

Edit:
I tried using 2.0 release as well as the latest commit version:
https://github.com/vantezzen/skip-silence/commit/c1f3cde829490df0b56fb87cf721ae13d43ff5b9
but both are not working. With 1.0 release it is working just fine.

**Comment by Roman-** [comment]
Hey @tillhanke ,

is this still an issue? I've tested with local mp4 file and everything seems to work just fine:

![mp4 local file](https://sun9-64.userapi.com/JZJmN6XjInqAg1ccRzAR5A2Csjj8HqjluLaM-A/A767IiA6ny8.jpg)

Ubuntu 16.04, Google Chrome Version 83.0.4103.116 (Official Build) (64-bit)

**Comment by tillhanke** [comment]
Yes it still persists. I am using Ubuntu 20.04 Chromium Version 83.0.4103.116 (snap)

It is no local mp4 file but a file from a website. Will test it with a local file as well.

![Screenshot from 2020-07-14 09-17-15](https://user-images.githubusercontent.com/11048183/87396409-1a57c900-c5b3-11ea-81c2-8760064b7134.png)

**Comment by tillhanke** [comment]
If I open the file locally it doesn't even recognize it at all.

**Comment by skoll43** [comment]
looking for a solution to this aswell

**Comment by mxbi** [comment]
Also having this issue

**Comment by vantezzen** [comment]
Chrome seems to have a lot of security measures around local files. Due to this, "Skip Silence" won't be able to access the volume levels of local files.

I just published v2.5 which should be released to the Chrome store in the next few days. This new update informs the user about local files not being supported and redirects them to the [special player](https://vantezzen.github.io/skip-silence/play/index.html) that uses some tricks to allow using "Skip Silence" on local files from there.
