### ISSUE TITLE
mp4 local file 

### ISSUE THREAD

**Issue by filemaster11** [vantezzen/skip-silence#3]
Hi, 

Great add on, saves so much time, thank you for your work.

I have been successfully using this extension for weeks, for playing .mp4 videos on chrome from my hard drive.
And now all of a sudden it doesn't work anymore, The icon is still purple but when I press the big red button, the soundbar doesn't move, like there is no sound. So it is just going fast forward all the time.
I'm doing everything the same, and I didn't change anything so I don't understand why it was working perfectly all this time and now it doesn't for no apparent reason. 
Maybe chrome or windows update?

It still works normally for youtube videos, but not for my local mp4 files.  
And when I play the mp4 video on chrome without turning on the extension, it works normally too, with sound.
And it still works fine on my laptop. My laptop is offline so it maybe didn't have the win10 or chrome update yet.

Thank you for your help.

![image](https://user-images.githubusercontent.com/60812968/74083787-39808680-4a68-11ea-86c7-768b93512897.png)

**Comment by vantezzen** [comment]
How do you open your local mp4 files? When I try to simply open them in chrome, chrome will disable all extensions for that tab so I can't use the extension at all. Do you have set any special settings?

**Comment by filemaster11** [comment]
As far as I know, nothing was changed in my settings. 
I usually just drag and drop a video to a new tab in chrome to play it. 
Try pressing refresh page button after opening a video. Because I have to do it to get the extension working. 
I could try to reinstall chrome to see if that will help.

**Comment by johannesCmayer** [comment]
I have the same problem. Refreshing the webpage does not help. The icon is not even purple for me when I am in a tab with a local mp4 file. For Youtube it works. I am on linux, maybe that is an issue.

```
NAME="Linux Mint"
VERSION="19.1 (Tessa)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 19.1"
VERSION_ID="19.1"
HOME_URL="https://www.linuxmint.com/"
SUPPORT_URL="https://forums.ubuntu.com/"
UBUNTU_CODENAME=bionic
```

**Comment by nicholastay** [comment]
I found that to use the extension on local files, first the extension needs to be enabled for file urls, specifically in the extension settings in chrome. But more importantly, chrome must also be launched with the `--allow-file-access-from-files` flag, otherwise no audio (there will be a CORS error and the extension won't work).

**Comment by vantezzen** [comment]
Chrome seems to have a lot of security measures around local files. Due to this, "Skip Silence" won't be able to access the volume levels of local files.

I just published v2.5 which should be released to the Chrome store in the next few days. This new update informs the user about local files not being supported and redirects them to the [special player](https://vantezzen.github.io/skip-silence/play/index.html) that uses some tricks to allow using "Skip Silence" on local files from there.

**Comment by ArniDagur** [comment]
The link for the "special player" seems to return a 404. It's a shame since my use case for this extension is to play local files.

**Comment by vantezzen** [comment]
@ArniDagur Are you using an old version of the extension? I recently moved the player due to Skip Silence 3.

You can still find it at https://vantezzen.github.io/skip-silence/player/

**Comment by ArniDagur** [comment]
The new link works. Thanks.

**Comment by barolo** [comment]
@vantezzen since there are workarounds which in fact do enable access to local-files wouldn't it be better to detect that instead forcing the web player which is a trick in itself?
