### ISSUE TITLE
Typo or wrong price on "Skip Silence Plus"

### ISSUE THREAD

**Issue by isogashiiman** [vantezzen/skip-silence#81]
**Describe the bug**
In the docs, and in the software, it is written everywhere that the Skip Silence Plus license costs $ 5.
But on gumroad. The price is $ 6

**To Reproduce**
- Click on '★' aside a premium feature.

**Expected behavior**
the unveiled price should match the expected price. 
Either you should change your price in gumroad, either you should edit the text in Skip Silence.

**Links**
- https://github.com/vantezzen/skip-silence/blob/1af9e8b27f5bf2d46a0c48d5d8b162aa498a2012/src/pages/popup/components/plusInfo.tsx#L37
- https://github.com/vantezzen/skip-silence/releases/tag/4.0.0

**Comment by vantezzen** [comment]
Thank you for the report.
Plus was originally planned to cost $5 but due to Gumroad's pricing, payment processing costs and currency conversion I updated the price to $6 - but it looks like I forgot to update the code accordingly.
I just published 7b4b1fe and updated the release to reflect the correct price - this change will be released in the next update.

**Comment by 9-2-1** [comment]
Hello, looks like the price has risen to $8, and another update is needed
