### ISSUE TITLE
Paid for key, no way to activate key

### ISSUE THREAD

**Issue by JacobTravers** [vantezzen/skip-silence#92]
I had to reinstall my operating system because my machine died during an update, now I am unable to find a way to regain the premium version I had paid for

**Comment by JacobTravers** [comment]
I was able to get to the "activate key" prompt by clicking here, so I will close this issue, however I think it would be a good idea to make this prompt a little more accessible or easier to get to.
![image](https://user-images.githubusercontent.com/46337843/140394447-2ab6f5de-a958-45de-a5f8-3d6f91b75ab0.png)

**Comment by JacobTravers** [comment]
Reopening because my activation key was marked invalid...

**Comment by vantezzen** [comment]
Hi there, sorry for the inconvenience caused by the license key.

Can you please send me an email to skipsilence@vantezzen.io with your license key and the email adress you bought it with? Gumroad is managing the license keys so I will have to look into their dashboard at why it might be failing to activate.

**Comment by JacobTravers** [comment]
the new key functions correctly on multiple machines, so I'm closing this issue.
